### ISSUE TITLE
smallIcon problem

### ISSUE THREAD

**Issue by joacodeviaje** [Neson/react-native-system-notification#4] opened 2016-01-12 05:41 UTC
Hi, is there any limitation/format for small icons? I'm trying to display my own, but I can only seem to get the default info icon.

**Comment by cpsiaki** [comment] 2016-01-16 15:42
I'm having the same problem

**Comment by Neson** [comment] 2016-01-19 07:14
It works for me here, as I put the `ic_custom_icon.png` in `android/app/src/main/res/*` (same as ic_launcher) then run:

```js
Notification.create({
  subject: 'Hi',
  smallIcon: 'ic_custom_icon'
});
```
Then I got: 
![12575974_10204166384399402_1207624486_n](https://cloud.githubusercontent.com/assets/3784687/12412058/e45ae36e-bebe-11e5-898e-f78cb1e7a954.jpg)

I guess this problem may be related to the Android version, may you help to provide further info that I can check it out?

**Comment by cpsiaki** [comment] 2016-01-19 13:05
does the file need to be a certain size/color?

**Comment by Neson** [comment] 2016-01-21 09:09
I placed the same icon with same sizes in `android/app/src/main/res/mipmap-hdpi`, `android/app/src/main/res/mipmap-mdpi`, `android/app/src/main/res/mipmap-xhdpi` and `/Users/Neson/Projects/Colorgy/ColorgyRNApp/android/app/src/main/res/mipmap-xxhdpi`.

The color doesn't matter, but it's usually white due to the design on android.

**Comment by Neson** [comment] 2016-03-21 11:15
Closing this for the reason that I think this problem is about Android system design, not a bug of this RN package ;)

**Closed by Neson** 2016-03-21 11:15 UTC
